import Head from 'next/head'
import Router from 'next/router'
import { useEffect, useState } from 'react'
import Postheader from '../components/Postheader'
import Videoitem from '../components/Videoitem'
import { auth, db } from '../firebase'






export default function Home() {

  const [isAuthenticated, setIsAuthenticated] = useState(false)
  const [shorts, setShorts] = useState([])
  

  useEffect(() => {
    const unsubscribe = auth.onAuthStateChanged((authUser) => {
      if (authUser) {
        setIsAuthenticated(true);
      } else {
        setIsAuthenticated(false);
      }
    })
    return unsubscribe;
  }, [])

  useEffect(() => {
    const unsubscribe = db
      .collection('shorts')
      .orderBy('timeStamps', 'desc')
      .onSnapshot((snapshot) => {
        setShorts(snapshot.docs.map((doc) => ({
          id: doc.id,
          shortsData: doc.data()
        })));
      })

    return unsubscribe;

  }, [])



  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='index'>
        <Postheader authenticated={isAuthenticated} />
        <div className="videoCon   overflow-y-scroll relative ">
          {shorts.map((short) => {

            return <Videoitem key={short.id} id={short.id} shortdata={short.shortsData}/>
         
          })
          }
        </div>
      </div>

    </div>
  )
}
